# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-30 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('first_name2', models.CharField(max_length=100, verbose_name='Prénom 2')),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=100, null=True, verbose_name='Adresse')),
                ('tel_number', models.CharField(max_length=100, null=True, verbose_name='Tel')),
                ('tel_number2', models.CharField(max_length=100, null=True, verbose_name='Tel 2')),
                ('gender', models.CharField(choices=[('man', 'Homme'), ('woman', 'Femme')], max_length=100, verbose_name='sexe')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Nom en arabe')),
                ('tel_number1', models.CharField(max_length=100, null=True, verbose_name='Téléphone 1')),
                ('tel_number2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone 2')),
                ('email1', models.EmailField(max_length=254, null=True, verbose_name='e-mail 1')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail 2')),
                ('adresse', models.CharField(max_length=200, null=True, verbose_name='Adresse')),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_arabic', models.CharField(max_length=255, verbose_name='Nom en arabe')),
                ('tel_number1', models.CharField(max_length=100, null=True, verbose_name='Téléphone 1')),
                ('tel_number2', models.CharField(max_length=100, null=True, verbose_name='Téléphone 2')),
                ('email1', models.EmailField(max_length=254, null=True, verbose_name='e-mail 1')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail 2')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('adresse', models.CharField(max_length=200, null=True, verbose_name='Adresse')),
                ('approval_number', models.CharField(max_length=100, verbose_name="Numéro de l'agrément")),
                ('type', models.CharField(choices=[('primary', 'Primaire'), ('middle', 'CEM'), ('high', 'Lycée')], max_length=100, verbose_name="Type de l'école")),
                ('pupils_number', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Schoolyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(max_length=50, verbose_name='2018-2017')),
                ('starts_at', models.CharField(max_length=50, verbose_name='commence à')),
                ('ends_at', models.CharField(max_length=50, verbose_name='se termine à')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Année Scolaire')),
                ('arabic_name', models.CharField(max_length=100, null=True, verbose_name='Année Scolaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='current_schoolyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schoolyears_list', to='client.Schoolyear'),
        ),
    ]
