# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-30 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('first_name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom 2')),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=100, null=True, verbose_name='Adresse')),
                ('tel_number', models.CharField(max_length=100, null=True, verbose_name='Tel')),
                ('tel_number2', models.CharField(max_length=100, null=True, verbose_name='Tel 2')),
                ('gender', models.CharField(choices=[('man', 'Homme'), ('woman', 'Femme')], max_length=100, verbose_name='sexe')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_activated', models.BooleanField(default=True, verbose_name='service actif')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='super administrateur')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.School')),
                ('schoolyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du niveau scolaire')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Nom de la matière (Arabe)')),
                ('code', models.CharField(max_length=100, verbose_name='Code ')),
                ('code_arabic', models.CharField(max_length=100, verbose_name='Code arabic')),
                ('type', models.CharField(blank=True, choices=[('primary', 'Primaire'), ('middle', 'CEM'), ('high', 'Lycée')], max_length=100, null=True, verbose_name='Type')),
                ('branch', models.CharField(blank=True, choices=[('Math', 'Mathématique'), ('Scientifique', 'Scientifique')], max_length=100, null=True, verbose_name='Branche')),
                ('rank', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.School')),
                ('schoolyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Nom de la matière (Arabe)')),
                ('code', models.CharField(max_length=100, verbose_name='Code ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='client.School')),
                ('schoolyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Schoolyear')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
