# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('scolarité', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarité.Level')),
                ('schoolyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Schoolyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolarité.Subject')),
            ],
        ),
    ]
