# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolarité', '0002_levelsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarité.Level'),
        ),
    ]
