# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-12 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_globallesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globallesson',
            old_name='levelsubject',
            new_name='subject',
        ),
    ]
