# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-13 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20201012_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globallesson',
            name='level',
        ),
        migrations.RemoveField(
            model_name='globallesson',
            name='subject',
        ),
        migrations.DeleteModel(
            name='GlobalLesson',
        ),
    ]
