# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20201013_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
