# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20201014_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
