# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
