# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
