# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0002_auto_20201002_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leçon.Lesson'),
        ),
    ]
