# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0004_auto_20201004_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
