# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0006_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='attachments'),
        ),
    ]
