# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0008_auto_20201004_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='leçon.Lesson')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
