# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0009_auto_20201004_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Image',
        ),
    ]
