# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0010_auto_20201004_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='lesson',
        ),
    ]
