# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0012_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
