# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import leçon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leçon', '0013_auto_20201004_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/', validators=[leçon.validators.validate_image_extension]),
        ),
    ]
